// packages/react-gpui/src/index.ts
import { createElement, forwardRef, useCallback, useRef, useState } from "react";
import type { ReactNode } from "react";
import type {
  HostNode,
  ImageProps,
  PressableProps,
  TextInputHandle,
  TextInputProps,
  TextProps,
  ViewHandle,
  ViewProps,
  VirtualListHandle,
  VirtualListProps,
} from "./renderer";
import { createStyleSheet } from "./style";

export {
  createRoot,
  SurfaceClosedError,
  type AccessibilityProps,
  type AnimationCompleteEvent,
  type HostKind,
  type HostNode,
  type Draggable,
  type DragDropHandler,
  type DragOverHandler,
  type ExternalFileDropHandler,
  type ImageObjectFit,
  type ImageProps,
  type KeyAction,
  type KeyEvent,
  type FocusEvent,
  type FocusHandler,
  type KeyHandler,
  type PointerAction,
  type PointerButton,
  type PointerEvent,
  type PointerDownOutsideEvent,
  type PointerDownOutsideHandler,
  type PointerHandler,
  type ScrollDeltaKind,
  type ScrollEvent,
  type ScrollHandler,
  type LayoutFrame,
  type LayoutHandler,
  type PressEventType,
  type PressHandler,
  type Root,
  type RootOptions,
  type TextInputHandle,
  type TextInputProps,
  type TextProps,
  type ViewHandle,
  type ViewProps,
  type PressableProps,
  type VirtualListHandle,
  type VirtualListProps,
  type WindowActivationHandler,
  type WindowResizeHandler,
  type Keybinding,
  type NotificationResponse,
  type NotificationResponseHandler,
  type NotificationAction,
} from "./renderer";
export type {
  MenuDefinition,
  MenuItem,
  NotificationOptions,
  PickFilesOptions,
  PickSavePathOptions,
  SurfaceKind,
  SurfaceOpenOptions,
  SurfaceOptions,
} from "./renderer";
export { createSurfaceHost, SurfaceIdReusedError, type SurfaceHost, type SurfaceHostOptions } from "./surface-host";
export {
  DEFAULT_MAX_PENDING_BYTES,
  MemoryTransport,
  StdioTransport,
  TransportTerminatedError,
  createProcessTerminationHandler,
  type ByteInput,
  type ByteInputEventListener,
  type ByteInputListener,
  type ByteOutput,
  type ByteOutputEventListener,
  type DrainListener,
  type ExitFunction,
  type StdioTransportOptions,
  type Transport,
  type TransportChunk,
  type TransportListener,
  type TransportTerminationCause,
  type TransportTerminationDetails,
  type TransportTerminationListener,
} from "./transport";
export {
  type BoxShadow,
  type BoxShadowInput,
  createStyleSheet,
  type AlignItems,
  type AlignSelf,
  type CursorStyle,
  type FlexDirection,
  type TextAlign,
  type Position,
  type FontStyle,
  type FontWeight,
  type JustifyContent,
  type NamedStyles,
  type Overflow,
  type Style,
  type StyleProp,
  type TextDecoration,
  type Transition,
  type TransitionEasing,
  type TransitionProperty,
} from "./style";
export {
  createAppearanceStore,
  createWindowSizeStore,
  useAppearance,
  useWindowSize,
  type Appearance,
  type AppearanceStore,
  type WindowSize,
  type WindowSizeStore,
} from "./hooks";
export const View = forwardRef<ViewHandle, ViewProps>((props, ref) => createElement("View", { ...props, ref }));
export const Image = forwardRef<HostNode, ImageProps>((props, ref) => createElement("Image", { ...props, ref }));
export const TextInput = forwardRef<TextInputHandle, TextInputProps>((props, ref) =>
  createElement("TextInput", { ...props, ref }),
);
export const Text = forwardRef<HostNode, TextProps>((props, ref) => createElement("Text", { ...props, ref }));
export const Pressable = forwardRef<HostNode, PressableProps>((props, ref) =>
  createElement("Pressable", { ...props, ref }),
);

function VirtualListImpl<T>(props: VirtualListProps<T>, ref: React.ForwardedRef<VirtualListHandle>) {
  const defaultCount = Math.min(props.data.length, props.initialNumToRender ?? 10);
  const [range, setRange] = useState<readonly [number, number]>(() => [0, defaultCount]);
  const rangeStart = Math.min(range[0], props.data.length);
  const storedRangeEnd = range[1] === 0 && defaultCount > 0 ? defaultCount : range[1];
  const rangeEnd = Math.min(Math.max(rangeStart, storedRangeEnd), props.data.length);
  const endReached = useRef(false);
  const onVisibleRange = useCallback(
    (start: number, end: number) => {
      const nextStart = Math.max(0, Math.min(start, props.data.length));
      const nextEnd = Math.max(nextStart, Math.min(end, props.data.length));
      setRange((previous) => (previous[0] === nextStart && previous[1] === nextEnd ? previous : [nextStart, nextEnd]));
      if (nextEnd >= props.data.length) {
        if (!endReached.current) {
          endReached.current = true;
          props.onEndReached?.();
        }
      } else {
        endReached.current = false;
      }
    },
    [props.data.length, props.onEndReached],
  );
  if (props.data.length === 0) {
    endReached.current = false;
    return props.emptyState ?? null;
  }
  const children: ReactNode[] = [];
  const keys = new Set<string>();
  for (let index = rangeStart; index < rangeEnd; index += 1) {
    const item = props.data[index];
    if (item === undefined) continue;
    const key = props.itemKey(item, index);
    if (typeof key !== "string" && typeof key !== "number")
      throw new TypeError("VirtualList itemKey must return a string or number");
    const keyString = String(key);
    if (keys.has(keyString))
      throw new TypeError(`VirtualList itemKey must be unique in committed range (duplicate ${keyString})`);
    keys.add(keyString);
    children.push(createElement("View", { key: keyString }, props.renderItem(item, index)));
  }
  return createElement(
    "VirtualList",
    {
      ref,
      style: props.style,
      __itemCount: props.data.length,
      __rangeStart: rangeStart,
      __rangeEnd: rangeEnd,
      __estimatedItemSize: props.estimatedItemSize,
      __overscan: props.overscan ?? 2,
      __onVisibleRange: onVisibleRange,
    },
    children,
  );
}

export const VirtualList = forwardRef(VirtualListImpl) as <T>(
  props: VirtualListProps<T> & { ref?: React.Ref<VirtualListHandle> },
) => React.ReactElement | null;

export const StyleSheet = {
  create: createStyleSheet,
} as const;

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      View: ViewProps;
      TextInput: TextInputProps;
      Text: TextProps;
      Pressable: PressableProps;
      Image: ImageProps;
      VirtualList: VirtualListProps<unknown>;
    }
  }
}

// packages/solid-gpui/src/index.ts
export {
  mountApplication,
  type ApplicationDefinition,
  type ApplicationOptions,
  type MountedApplication,
} from "./application";
export type {
  ClipboardImage,
  ClipboardImageFormat,
  ExtensionField,
  ExtensionProperties,
  ExtensionValue,
} from "./protocol";
export { ICON_NAMES } from "./protocol";
import { createMemo, createSignal, mapArray } from "solid-js";
import { createHostElement } from "./renderer";
import type {
  HostNode,
  HostKind,
  HostNodeInternal,
  HostProps,
  ImageProps,
  IconProps,
  PressableProps,
  TextInputHandle,
  TextInputProps,
  TextProps,
  ViewHandle,
  ViewProps,
  VirtualListHandle,
  SolidChild,
  VirtualListProps,
} from "./renderer/types";
import { createStyleSheet } from "./style";

export {
  createRoot,
  createHostElement,
  createExtensionElement,
  defineExtensionComponent,
  solidRenderer,
  SurfaceClosedError,
  type AccessibilityProps,
  type AnimationCompleteEvent,
  type HostKind,
  type HostNode,
  type SolidChild,
  type SolidElement,
  type Draggable,
  type DragDropHandler,
  type DragOverHandler,
  type ExternalFileDropHandler,
  type ImageObjectFit,
  type ImageProps,
  type IconProps,
  type IconName,
  type KeyAction,
  type KeyEvent,
  type FocusEvent,
  type FocusHandler,
  type KeyHandler,
  type PointerButton,
  type PointerEvent,
  type PointerMoveEvent,
  type PointerDownOutsideEvent,
  type PointerDownOutsideHandler,
  type PointerHandler,
  type PointerMoveHandler,
  type ScrollDeltaKind,
  type ScrollEvent,
  type ScrollHandler,
  type LayoutFrame,
  type LayoutHandler,
  type PressEventType,
  type PressHandler,
  type Root,
  type RootOptions,
  type TextInputHandle,
  type TextInputProps,
  type TextProps,
  type ViewHandle,
  type ViewProps,
  type PressableProps,
  type VirtualListHandle,
  type VirtualListProps,
  type WindowActivationHandler,
  type WindowResizeHandler,
  type Keybinding,
  type NotificationResponse,
  type NotificationResponseHandler,
  type NotificationAction,
  type MenuDefinition,
  type MenuItem,
  type NotificationOptions,
  type PickFilesOptions,
  type PickSavePathOptions,
  type SurfaceKind,
  type SurfaceOpenOptions,
  type SurfaceOptions,
  type ExtensionDescriptor,
  type ExtensionEvent,
  type ExtensionEventHandler,
  type ExtensionProps,
  type ExtensionComponentProps,
} from "./renderer";
export { createSurfaceHost, SurfaceIdReusedError, type SurfaceHost, type SurfaceHostOptions } from "./surface-host";
export {
  MemoryTransport,
  TransportTerminatedError,
  type DisposableTransport,
  type Transport,
  type TransportChunk,
  type TransportListener,
  type TransportTerminationCause,
  type TransportTerminationDetails,
  type TransportTerminationListener,
} from "./transport";
export {
  type BoxShadow,
  type BoxShadowInput,
  createStyleSheet,
  type AlignItems,
  type AlignSelf,
  type CursorStyle,
  type FlexDirection,
  type TextAlign,
  type Position,
  type FontStyle,
  type FontWeight,
  type JustifyContent,
  type NamedStyles,
  type Overflow,
  type Style,
  type StyleProp,
  type TextDecoration,
  type Transition,
  type TransitionEasing,
  type TransitionProperty,
} from "./style";
export {
  createAppearanceStore,
  createWindowSizeStore,
  useAppearance,
  useWindowSize,
  type Appearance,
  type AppearanceStore,
  type WindowSize,
  type WindowSizeStore,
} from "./hooks";

function hostComponent<Props extends object>(kind: HostKind): (props: Props) => HostNodeInternal {
  return (props: Props): HostNodeInternal => createHostElement(kind, props as HostProps);
}

export const View = hostComponent<ViewProps>("View");
export const Image = hostComponent<ImageProps>("Image");
export const TextInput = hostComponent<TextInputProps>("TextInput");
export const Icon = hostComponent<IconProps>("Icon");
export const Text = hostComponent<TextProps>("Text");
export const Pressable = hostComponent<PressableProps>("Pressable");

export function VirtualList<T>(props: VirtualListProps<T>): SolidChild {
  const initialCount = Math.min(props.data.length, props.initialNumToRender ?? 10);
  const [range, setRange] = createSignal<readonly [number, number]>([0, initialCount]);
  let endReached = false;
  const onVisibleRange = (start: number, end: number): void => {
    const nextStart = Math.max(0, Math.min(start, props.data.length));
    const nextEnd = Math.max(nextStart, Math.min(end, props.data.length));
    setRange([nextStart, nextEnd]);
    if (nextEnd >= props.data.length) {
      if (!endReached) {
        endReached = true;
        props.onEndReached?.();
      }
    } else {
      endReached = false;
    }
  };
  const committedRange = createMemo<readonly [number, number]>(() => {
    const count = props.data.length;
    const [start, end] = range();
    // A previously empty list or a filter shorter than the old viewport must
    // publish real initial rows, never an inverted/out-of-bounds wire range.
    if (start >= count || end <= start) return [0, Math.min(count, props.initialNumToRender ?? 10)];
    return [start, Math.min(end, count)];
  });
  // Retain only the current window. mapArray gives each row its own Solid owner
  // and disposes it when it leaves; overlapping rows retain their host identity.
  type Row = { key: string; item: T; index: number };
  let previousRows = new Map<string, Row>();
  const visibleRows = createMemo(() => {
    const [start, end] = committedRange();
    const rows: Row[] = [];
    const nextRows = new Map<string, Row>();
    const keys = new Set<string>();
    for (let index = start; index < Math.min(end, props.data.length); index += 1) {
      const item = props.data[index];
      if (item === undefined) continue;
      const key = props.itemKey(item, index);
      if (typeof key !== "string" && typeof key !== "number") {
        throw new TypeError("VirtualList itemKey must return a string or number");
      }
      const normalized = String(key);
      if (keys.has(normalized)) {
        throw new TypeError(`VirtualList itemKey must be unique in committed range (duplicate ${normalized})`);
      }
      keys.add(normalized);
      const previous = previousRows.get(normalized);
      const row =
        previous && Object.is(previous.item, item) && previous.index === index
          ? previous
          : { key: normalized, item, index };
      rows.push(row);
      nextRows.set(normalized, row);
    }
    previousRows = nextRows;
    return rows;
  });
  const visibleChildren = mapArray(visibleRows, (row) =>
    createHostElement("View", { key: row.key, children: props.renderItem(row.item, row.index) }),
  );
  const node = createHostElement("VirtualList", {
    get style() {
      return props.style;
    },
    get ref() {
      return props.ref;
    },
    get __itemCount() {
      return props.data.length;
    },
    get __rangeStart() {
      return committedRange()[0];
    },
    get __rangeEnd() {
      return committedRange()[1];
    },
    get __estimatedItemSize() {
      return props.estimatedItemSize;
    },
    get __overscan() {
      return props.overscan ?? 2;
    },
    __onVisibleRange: onVisibleRange,
    get children() {
      return visibleChildren();
    },
  });
  return () => {
    if (props.data.length === 0) {
      endReached = false;
      return props.emptyState ?? null;
    }
    return node;
  };
}

export const StyleSheet = { create: createStyleSheet } as const;
